[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sr4ha"
version = "0.1.0"
description = "Hybrid System Learning with Symbolic Regression"

dependencies = [
    "polars",
    "ruamel.yaml",
    "matplotlib",
    "pysr",
    "optuna"
]