file: "data/bouncingball/shifted-data.csv"
eval: "data/bouncingball/eval_data.csv"
gt-learn: "results/ball/gt_switches.csv"
gt-eval: "results/ball/gt_switches.csv"
features:
  - x1
  - x2
dt-features:
  - x1
  - x2

start_width: 50
step_width: 50
target_var: x0
step_iterations: 5
file_prefix: "ball"
hist_length: 5
gt-groups: 1

segmentation:
  criterion: 
    name: "decrease"
    kwargs:
      saturation: 1e-4
  kwargs:
    niterations: 20
    verbosity: 0
    complexity_of_constants: 10
    parsimony: 1e-6
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators:

grouping:
  criterion:
    name: "preserving_group_loss"
    kwargs:
      factor: 1.5
  kwargs:
    niterations: 20
    verbosity: 0
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    complexity_of_constants: 10
    parsimony: 1e-6
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators: