file: "data/bouncingball/shifted-data.csv"
features:
  - x1
  - x2

start_width: 10
step_width: 10
target_var: 
  - x0
mode_var: m
threshold: 0.5
learner: "SymbolicRegressor"

learner-kwargs:
  niterations: 10
  verbosity: 0
  parsimony: 5
  random_state: 42
  deterministic: true
  procs: 0
  multithreading: false
  binary_operators:
    - "-"
    - "+"
    - "*"
  unary_operators:

segmentation:
  criterion: 
    name: "threshold_error"
    kwargs:
      threshold: 0.5
