file: "data/boiler/boiler_data.csv"
eval: "data/boiler/boiler_eval_data.csv"
gt-learn: "data/boiler/gt_switches.csv"
gt-eval: "data/boiler/gt_switches_eval.csv"
features:
  - x
dt-features:
  - x

start_width: 30
step_width: 1
target_var: xdot
step_iterations: 5
file_prefix: "boiler"
hist_length: 5
gt-groups: 2

segmentation:
  criterion: 
    name: "decrease"
    kwargs:
      saturation: 1e-4
  kwargs:
    niterations: 20
    verbosity: 0
    complexity_of_constants: 1
    parsimony: 1e-6
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    binary_operators:
      - "-"
      - "+"
      - "*"
    unary_operators:

grouping:
  criterion:
    name: "preserving_group_loss"
    kwargs:
      factor: 1.6
  kwargs:
    niterations: 20
    verbosity: 0
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    complexity_of_constants: 1
    parsimony: 1e-6
    binary_operators:
      - "-"
      - "+"
      - "*"
    unary_operators: