file: "data/electricCircuit/circuit_data.csv"
features:
  - I2
  - U1
  - U5
  - I5
  - R3
  - R4
  - R5

start_width: 300
step_width: 100
step_iterations: 5
file_prefix: "test"
hist_length: 5
criterion: "strict_increase"

kwargs:
  niterations: 40
  verbosity: 0
  complexity_of_constants: 10
  binary_operators:
    - "-"
    - "+"
    - "*"
    - "/"
  unary_operators:

target_var: 'I4'
