file: "data/converter/short_wto_zeros_data_converter_omega400e3_beta40e3_Q10_theta60.csv"
features:
  - t
  - w1
  - w2

start_width: 100
step_width: 10
step_iterations: 15
file_prefix: "cluster"
hist_length: 5
criterion: 
  name: "decrease"
  kwargs:
    saturation: 1e-7
cluster_criterion:
  factor: 5

kwargs:
  niterations: 40
  verbosity: 0
  binary_operators:
    - "-"
    - "+"
    - "*"
    - "/"
  unary_operators:
    - "sqrt"

target_var: 'w2'
derivative: true
