file: "data/linear/trapezoid_data.csv"
features:
  - x

start_width: 5
step_width: 1
target_var: y
mode_var: m
threshold: 0.01
learner: "LinearRegressor"

learner-kwargs: {}

segmentation:
  criterion: 
    name: "threshold_error"
    kwargs:
      threshold: 0.01
