file: "data/population/population_data.csv"
features:
  - P
  - t
  - K
  - r_1
  - r_2
  - r_3
  - P_0
  - P_1
  - P_2

start_width: 50
step_width: 10
step_iterations: 5
file_prefix: "population"
hist_length: 5
criterion: 
  name: "decrease"
  kwargs:
    saturation: 1e-7

kwargs:
  niterations: 200
  verbosity: 0
  complexity_of_constants: 10
  parsimony: 1e-6
  binary_operators:
    - "-"
    - "+"
    - "*"
    - "/"
  unary_operators:
    - "exp"
    - "neg"

target_var: 'P'
derivative: true
