file: "examples/twotank/data_onetank_withsubst.csv"
features:
  - mQp
  - y1
  - A1
  - Cvb
  - ysqrt
window:
  start: 0
  length: 370

kwargs:
  population_size: 500
  stopping_criteria: 1e-5
  generations: 30
  parsimony_coefficient: 1
  p_crossover: 0.3
  p_subtree_mutation: 0.2
  p_hoist_mutation: 0.05
  p_point_mutation: 0.3
  p_point_replace: 0.3
  max_samples: 1.0
  verbose: 1
  random_state: 0
  const_range: null
  
function_set:
  - sub
  - add
  - mul
additional_functions:
  - mydiv
custom_metric: mape

target_var: 'dy'
