file: "data/twotank/data_withsubst.csv"
features:
  - mQp
  - y1
  - y2
  - A1
  - Cvb
  - sumsqrt

start_width: 41
step_width: 1
step_iterations: 29
file_prefix: "two-tank-sub"
hist_length: 5

segmentation:
  criterion: 
    name: "decrease"
    kwargs:
      saturation: 1.2842316619362689e-08
  kwargs:
    niterations: 156
    verbosity: 0
    complexity_of_constants: 10
    parsimony: 0.7627879195993068
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators:

grouping:
  criterion:
    name: "preserving_group_loss"
    kwargs:
      factor: 0.7910069852843661
  kwargs:
    niterations: 204
    verbosity: 0
    random_state: 42
    deterministic: true
    procs: 0
    populations: 15
    multithreading: false
    complexity_of_constants: 10
    parsimony: 0.44838474380558097
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators:

target_var: 'dy'
