file: "data/twotank/data_withsubst.csv"
eval: "data/twotank/eval_twotank_withsubst.csv"
gt-learn: "results/two_tank/gt_switches.csv"
gt-eval: "results/two_tank/gt_eval.csv"
features:
  - mQp
  - y1
  - y2
  - A1
  - Cvb
dt-features:
  - mQp
  - y1
  - y2
  - A1
  - Cvb
  - mUb

start_width: 60
step_width: 50
step_iterations: 7
file_prefix: "two-tank-nsub"
hist_length: 5

segmentation:
  criterion: 
    name: "decrease"
    kwargs:
      saturation: 8.75e-9
  kwargs:
    niterations: 225
    verbosity: 0
    complexity_of_constants: 10
    parsimony: 0.44
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators:
      - "sqrt"

grouping:
  criterion:
    name: "preserving_group_loss"
    kwargs:
      factor: 0.72
  kwargs:
    niterations: 190
    verbosity: 0
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    complexity_of_constants: 10
    parsimony: 0.74
    populations: 15
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators:
      - "sqrt"

target_var: 'dy'
