file: "data/twotank/data_withsubst.csv"
eval: "data/twotank/eval_twotank_withsubst.csv"
gt-learn: "results/two_tank/gt_switches.csv"
gt-eval: "results/two_tank/gt_eval.csv"
features:
  - mQp
  - y1
  - y2
  - A1
  - Cvb
  - sumsqrt
dt-features:
  - mQp
  - y1
  - y2
  - A1
  - Cvb
  - sumsqrt
  - mUb

start_width: 40
step_width: 1
step_iterations: 25
file_prefix: "two-tank-sub"
hist_length: 5

segmentation:
  criterion: 
    name: "decrease"
    kwargs:
      saturation: 1.28e-8
  kwargs:
    niterations: 150
    verbosity: 0
    complexity_of_constants: 10
    parsimony: 0.76
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators:

grouping:
  criterion:
    name: "preserving_group_loss"
    kwargs:
      factor: 0.79
  kwargs:
    niterations: 200
    verbosity: 0
    random_state: 42
    deterministic: true
    procs: 0
    populations: 15
    multithreading: false
    complexity_of_constants: 10
    parsimony: 0.45
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators:

target_var: 'dy'
