file: "examples/twotank/data_onetank.csv"
features:
  - mQp
  - y1
  - mQ0
window:
  start: 0
  length: 370

kwargs:
  population_size: 500
  stopping_criteria: 1e-5
  generations: 30
  parsimony_coefficient: 1e-5
  p_crossover: 0.3
  p_subtree_mutation: 0.2
  p_hoist_mutation: 0.05
  p_point_mutation: 0.3
  p_point_replace: 0.3
  max_samples: 1.0
  verbose: 1
  random_state: 0
  
function_set:
  - sub
  - add
  - mul
  - abs
  - sqrt
additional_functions:
  - mydiv
  - sign

target_var: 'y1'
target_manipulation: differentiate
