file: "data/twotank/data_withsubst.csv"
features:
  - mQp
  - y1
  - y2
  - A1
  - Cvb
  - sumsqrt

start_width: 50
step_width: 10
step_iterations: 5
file_prefix: "test"
hist_length: 5
criterion: 
  name: "decrease"
  kwargs:
    saturation: 1e-7
cluster_criterion:
  factor: 5

kwargs:
  niterations: 40
  verbosity: 0
  complexity_of_constants: 10
  parsimony: 1e-6
  binary_operators:
    - "-"
    - "+"
    - "*"
    - "/"
  unary_operators:

target_var: 'dy'
