file: "examples/twotank/data_withsubst.csv"
type: PySR
features:
  - mQp
  - y1
  - y2
  - h1
  - mUb
  - A1
  - Cvb
  - sumsqrt
window:
  start: 0
  length: 370

kwargs:
  complexity_of_constants: 10
  binary_operators:
    - "-"
    - "+"
    - "*"
    - "/"
  unary_operators:
    - "sign"

target_var: 'dy'
