file: "data/twotank/data_withsubst.csv"
features:
  - mQp
  - y1
  - y2
  - A1
  - Cvb

start_width: 62
step_width: 47
step_iterations: 71
file_prefix: "two-tank-nsub"
hist_length: 5

segmentation:
  criterion: 
    name: "decrease"
    kwargs:
      saturation: 8.752605317897294e-09
  kwargs:
    niterations: 228
    verbosity: 0
    complexity_of_constants: 10
    parsimony: 0.43910625062004516
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators:
      - "sqrt"

grouping:
  criterion:
    name: "preserving_group_loss"
    kwargs:
      factor: 0.7198352525294622
  kwargs:
    niterations: 195
    verbosity: 0
    random_state: 42
    deterministic: true
    procs: 0
    multithreading: false
    complexity_of_constants: 10
    parsimony: 0.7441674257647625
    populations: 18
    binary_operators:
      - "-"
      - "+"
      - "*"
      - "/"
    unary_operators:
      - "sqrt"

target_var: 'dy'
